# 14112018 - Simple HMM implementation to understand the parameters to use for the hmmlearn module

In [2]:
import numpy as np
import matplotlib.pyplot as plt

from hmmlearn import hmm

In [99]:
shape = (8,2)
seq = np.array([0,1,2,3.4,5.4,3.4,2,8,1,2,3,4,1,2,4,3]).reshape(shape)
print(seq)
print(seq.shape)

model = hmm.GaussianHMM(n_components=4, params='stmc', init_params='')
model.fit(seq)

[[0.  1. ]
 [2.  3.4]
 [5.4 3.4]
 [2.  8. ]
 [1.  2. ]
 [3.  4. ]
 [1.  2. ]
 [4.  3. ]]
(8, 2)


GaussianHMM(algorithm='viterbi', covariance_type='diag', covars_prior=0.01,
      covars_weight=1, init_params='', means_prior=0, means_weight=0,
      min_covar=0.001, n_components=4, n_iter=10, params='stmc',
      random_state=None, startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
      verbose=False)

In [100]:
model.score(seq, lengths=[4])

-2.462017448172954

In [101]:
model.score(seq)

-8.159831820634924

In [102]:
model.score_samples(seq)

(-8.159831820634924, array([[1.97077381e-160, 1.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [1.00000000e+000, 4.36531863e-038, 0.00000000e+000,
         2.02334404e-021],
        [6.97283420e-113, 1.09055226e-068, 0.00000000e+000,
         1.00000000e+000],
        [1.09055226e-068, 3.42996550e-090, 1.00000000e+000,
         1.92837647e-155],
        [3.42996483e-090, 1.00000000e+000, 0.00000000e+000,
         3.29260873e-116],
        [1.00000000e+000, 1.58988471e-051, 0.00000000e+000,
         3.95308255e-026],
        [1.29948982e-049, 1.00000000e+000, 0.00000000e+000,
         1.48587912e-030],
        [5.22565323e-003, 2.11913757e-045, 0.00000000e+000,
         9.94774347e-001]]))

In [103]:
model.score_samples(seq)

(-8.159831820634924, array([[1.97077381e-160, 1.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [1.00000000e+000, 4.36531863e-038, 0.00000000e+000,
         2.02334404e-021],
        [6.97283420e-113, 1.09055226e-068, 0.00000000e+000,
         1.00000000e+000],
        [1.09055226e-068, 3.42996550e-090, 1.00000000e+000,
         1.92837647e-155],
        [3.42996483e-090, 1.00000000e+000, 0.00000000e+000,
         3.29260873e-116],
        [1.00000000e+000, 1.58988471e-051, 0.00000000e+000,
         3.95308255e-026],
        [1.29948982e-049, 1.00000000e+000, 0.00000000e+000,
         1.48587912e-030],
        [5.22565323e-003, 2.11913757e-045, 0.00000000e+000,
         9.94774347e-001]]))

In [104]:
model.decode(seq)

(-8.16507117534347, array([1, 0, 3, 2, 1, 0, 1, 3]))

In [77]:
seq_2 = np.array([1,2,3,4]).reshape(1,4)
model.predict(seq_2)

ValueError: shapes (1,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)

In [41]:
print(model.transmat_)

[[1.00000000e+000 0.00000000e+000 0.00000000e+000 2.31856045e-170]
 [5.61566959e-133 0.00000000e+000 0.00000000e+000 1.00000000e+000]
 [0.00000000e+000 1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.00000000e+000 0.00000000e+000 0.00000000e+000 2.37034179e-170]]


In [42]:
print(model.n_features)

4


In [43]:
print(model.startprob_)

[0. 0. 1. 0.]


In [44]:
print(model.covars_)

[[[0.01 0.   0.   0.  ]
  [0.   0.01 0.   0.  ]
  [0.   0.   0.01 0.  ]
  [0.   0.   0.   0.01]]

 [[0.01 0.   0.   0.  ]
  [0.   0.01 0.   0.  ]
  [0.   0.   0.01 0.  ]
  [0.   0.   0.   0.01]]

 [[0.01 0.   0.   0.  ]
  [0.   0.01 0.   0.  ]
  [0.   0.   0.01 0.  ]
  [0.   0.   0.   0.01]]

 [[0.01 0.   0.   0.  ]
  [0.   0.01 0.   0.  ]
  [0.   0.   0.01 0.  ]
  [0.   0.   0.   0.01]]]


In [45]:
model.predict_proba(seq_2)

array([[0., 0., 1., 0.]])

In [46]:
model.score_samples(seq_2)

(-162.46541376084224, array([[0., 0., 1., 0.]]))

In [69]:
seq_3 = np.array([1,18,14,13]).reshape(-1,1)
print(seq_3)
model.score_samples(seq_3)

[[ 1]
 [18]
 [14]
 [13]]


(-312.2342379380166, array([[1.00000000e+000, 7.40065901e-026, 4.16215786e-017,
         0.00000000e+000],
        [2.69267031e-224, 1.00000000e+000, 3.59448654e-085,
         0.00000000e+000],
        [1.19145586e-141, 1.00000000e+000, 1.22357581e-052,
         0.00000000e+000],
        [1.56205012e-119, 1.00000000e+000, 4.59250118e-045,
         0.00000000e+000]]))

In [27]:
print(model.n_components)

4


In [106]:
sample_arr = np.array([1,1,1,1])
print(np.reshape(sample_arr, (-1, 3)))

ValueError: cannot reshape array of size 4 into shape (3)